### ISSUE TITLE
Dependency on package cryst

### ISSUE THREAD

**Issue by vendramin** [vendramin/YB#57]
The function LinearRepresentationOfStructureGroup uses this package. Would it be possible to exclude this function if the package is not there? In any case, cryst should be loaded before YangBaxter.

**Comment by olexandr-konovalov** [comment]
Then what about #58? Cryst does not require compilation, so it should be runnable anywhere.

**Comment by olexandr-konovalov** [comment]
We decided to make the package suggested, and load the function dependently on whether it is available or not. I will implement this.

**Comment by olexandr-konovalov** [comment]
@vendramin Removing `LinearRepresentationOfStructureGroup` will further require to remove ` IYBBrace`. One more time, I have doubts - do we really want to make both of these optionally available? 

First of all, the description of this task is perhaps outdated. It is `IYBBrace` which uses functions from Cryst:`AffineCrystGroupOnLeft`, `PointGroup` and `PointHomomorphism`. 

But the main point is that Cryst is redistributed with GAP, and has no non-standard dependencies (it requires polycyclic package, and both do not require compilation). So it will be much simpler to merge https://github.com/gap-packages/YangBaxter/pull/58 rather than conditionally load some code...

**Comment by olexandr-konovalov** [comment]
@vendramin see now new #77 by @fingolfin please - as I said above, Cryst is redistributed with GAP, and has no non-standard dependencies (it requires polycyclic package, and both do not require compilation). So it will be much simpler to merge #77 rather than conditionally load some code...

**Comment by olexandr-konovalov** [comment]
Closed by #77 - thanks @fingolfin

**Comment by vendramin** [comment]
What is your suggestion here? The functions you mention are useful, I would not remove them.

**Comment by fingolfin** [comment]
We resolved this in April by merging Pr #77
